# Generated by Django 4.2.7 on 2023-12-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='nombre',
        ),
    ]
