# Generated by Django 4.2.7 on 2023-12-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_name_course_nombre_rename_name_subject_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='course',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='course',
            new_name='curso',
        ),
    ]
