# Generated by Django 4.2.7 on 2023-12-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_course_curso_rename_course_staff_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstaff',
            old_name='staff',
            new_name='docente',
        ),
        migrations.RenameField(
            model_name='leavereportstaff',
            old_name='staff',
            new_name='docente',
        ),
        migrations.RenameField(
            model_name='notificationstaff',
            old_name='staff',
            new_name='docente',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='staff',
            new_name='docente',
        ),
    ]
