# Generated by Django 4.2.7 on 2023-12-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_staff_feedbackstaff_docente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstaff',
            old_name='feedback',
            new_name='retroalimentación',
        ),
        migrations.RenameField(
            model_name='feedbackstudent',
            old_name='feedback',
            new_name='retroalimentación',
        ),
    ]
